# Generated by Django 5.2.5 on 2025-11-25 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='age',
            new_name='number_of_item',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
