# Generated by Django 5.2.5 on 2025-11-25 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_course_student_item_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='Inventory',
        ),
    ]
