# Generated by Django 5.2.5 on 2025-09-04 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.CharField(max_length=10)),
                ('head_of_department', models.CharField(max_length=100)),
                ('no_of_professors', models.IntegerField()),
                ('no_of_students', models.IntegerField()),
                ('units_per_sem', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('department_head', models.CharField(max_length=100)),
                ('instructor_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=10)),
                ('instructor_id', models.IntegerField()),
                ('students_per_dept', models.IntegerField()),
                ('subject_id', models.IntegerField()),
                ('day_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField(auto_now_add=True)),
                ('address', models.CharField(max_length=100)),
                ('student_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('no_units', models.IntegerField()),
                ('semesters', models.IntegerField()),
                ('schedule', models.DateField(auto_now_add=True)),
                ('subject_id', models.IntegerField()),
            ],
        ),
    ]
