# Generated by Django 5.2.5 on 2025-09-04 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='name_id',
            new_name='course_id',
        ),
    ]
