# Generated by Django 5.2.5 on 2025-09-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0002_rename_students_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='phone_number',
            field=models.IntegerField(max_length=100),
        ),
    ]
