# Generated by Django 5.2.5 on 2025-09-09 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0003_alter_instructor_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='department_head',
            new_name='department',
        ),
    ]
