# Generated by Django 5.2.5 on 2025-09-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0004_rename_department_head_instructor_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_id',
            field=models.CharField(max_length=100),
        ),
    ]
