# Generated by Django 5.2.5 on 2025-09-09 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0005_alter_instructor_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='subject_id',
            field=models.CharField(max_length=100),
        ),
    ]
