# Generated by Django 5.2.5 on 2025-09-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0006_alter_schedule_subject_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='date_of_birth',
            new_name='date_birth',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
