# Generated by Django 5.2.5 on 2025-09-09 02:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0007_rename_date_of_birth_student_date_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day_time',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
