# Generated by Django 5.2.5 on 2025-09-09 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0008_alter_schedule_day_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_birth',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='schedule',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
