# Generated by Django 5.2.5 on 2025-09-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0009_alter_student_date_birth_alter_subject_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='schedule',
            field=models.DateField(blank=True, null=True),
        ),
    ]
